names: 
  file: "names.txt" # name of file that contains a list of names
  # data: ["sam", "tom", "jim", "grace", "bill"] # array of names that is unioned with the above file
passwords: 
  file: "passwords.txt"
  # data: ["password1", "password2", "password3"]
canAllocateSelf: false # can you be allocated yourself
timeout: 5s # timeout of finding a suitable allocation

rules: # rules per persons of allocations
  sam: 
    cannotGet: 
      - "matt"
      - "grace"
      - "tom"
      - "jim"
      - "bill"
      - "john"
      - "helloya"